services:

  php:
    build:
      context: php-apache
    ports:
      - "${APP_PORT}:80"
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - "${APP_DIR}:/var/www/html"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysqldb:
    image: arm64v8/mysql:8.0.30-oracle
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./databases/mysqldb:/var/lib/mysql
    command: mysqld --sql_mode='' --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "127.0.0.1:${PMA_PORT}:80"
    environment:
      PMA_HOST: mysqldb
      PMA_USER: user
      PMA_PASSWORD: pass
      UPLOAD_LIMIT: 5G