version: "3.8"

services:

  php:
    build:
      context: php-apache
    ports:
      - "${APP_PORT}:80"
    volumes:
      - "${APP_DIR}:/var/www/html"

  mariadb:
    image: mariadb:10.7
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./databases/mariadb:/var/lib/mysql
    command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "127.0.0.1:${PMA_PORT}:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: user
      PMA_PASSWORD: pass
      UPLOAD_LIMIT: 1G